### ISSUE TITLE
accessing Config in get_metric_types(Config cfg)

### ISSUE THREAD

**Issue by krzysztofx** [intelsdi-x/snap-plugin-lib-cpp#13]
Correct me If I'm wrong, but  this method doesn't reflect properly it's native golang counterpart GetMetricTypes(ConfigType) ([]MetricType, error).   There's missing ConfigType implementation, so we cannot access nested config attributes.

**Comment by marcin-krolik** [comment]
Referring to call with @krzysztofx - `snap-plugin-lib-cpp` provides similar `Config` access mechnism to those implemented in `snap-plugin-lib-go`. 
User is able to access configuration item via methods `get_bool()`, `get_int()` and `get_string()`.
