### ISSUE TITLE
Plugin::Metric Get methods are not const

### ISSUE THREAD

**Issue by RomanUlan** [intelsdi-x/snap-plugin-lib-cpp#15]
Code do not fulfill "const correct rule".
Read-only methods (like: _Plugin::Metric::ns()_ and _Plugin::Metric::dynamic_ns_elements()_) should be _const_ and return values or const& to class properties.

**Comment by marcin-krolik** [comment]
Goog catch @RomanUlan . I will provide fix soon

**Comment by marcin-krolik** [comment]
Fixed
