### ISSUE TITLE
Provided compiled procol buffers are not up to date with Snap Core

### ISSUE THREAD

**Issue by skonefal** [intelsdi-x/snap-plugin-lib-cpp#43]
Bug connected to #34.

Compiled Protobufs in c++ library are from July, and last change of protobufs in Snap is in November.
They should be refreshed. 

By chance they actually work, but for example Snap protobuf supports metrics in `uint64`, and protobuf in cpp-library does not.

**Comment by katarzyna-z** [comment]
Resolved by #44
