### ISSUE TITLE
Collecting dynamic metrics in "collect_metrics" works badly.

### ISSUE THREAD

**Issue by MrDarthShoe** [intelsdi-x/snap-plugin-lib-cpp#52]
In collect_metrics user must modify incoming vector of metrics by reference and delete dynamic ones. Otherwise, snaptel receives metrics with value "*". 

Now (bad):

    void collect_metrics(std::vector<Plugin::Metric> &metrics);
         (modify incoming "metrics"here)

In future (good):

    std::vector<Plugin::Metric> collect_metrics(std::vector<Plugin::Metric> &metrics);
          (return new vector of metrics with dynamic elements included)

It would be great if collect_metrics could return vector of metrics (just like in [snap-plugin-lib-go](https://github.com/intelsdi-x/snap-plugin-lib-go)) . 

      func (RandCollector) CollectMetrics(mts []plugin.Metric) ([]plugin.Metric, error)

**Comment by katarzyna-z** [comment]
Resolved in #54
